version: '3.8'

services:
  bot:
    build: .
    container_name: nexuscoders-whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
      - ./temp:/app/temp
      - ./assets:/app/assets
      - ./logs:/app/logs
